// Generated by CoffeeScript 1.8.0
(function() {
  window.templates = {
    "ipsumText": "{{#paragraphs}}<p>{{.}}</p><br>{{/paragraphs}}",
    "ipsumJSON": "{{json}}",
    "optionType": "<li><a href='#' data-type='{{type}}'>{{type}}{{#isCurrent}} (current){{/isCurrent}}</a></li>",
    "optionParagraphs": "<li><a href='#' data-paragraphs='{{num}}'>{{num}}{{#isCurrent}} (current){{/isCurrent}}</a></li>",
    "optionFormat": "<li><a href='#' data-format='{{format}}'>{{format}}{{#isCurrent}} (current){{/isCurrent}}</a></li>"
  };

}).call(this);
