// Generated by CoffeeScript 1.8.0
(function() {
  window.terms = {
    "Trello": ["card", "board", "at a glance", "Trello", "Taco", "lists", "list of lists", "checklists", "Chorizo", "Pete", "Trello Gold", "Business Class", "visual", "free", "attachment", "drag and drop", "members", "organization"],
    "Hodor": ["hodor", "hodor", "hodor", "hodor", "hodor", "hodor", "HODOR", "Hodor"],
    "Escape": ["<p>", "<B>YESIR</B>", "<script>alert('good times')</script>", "</p>", "</html>", "Hey", "<img src='/' width='500' height='300'>"]
  };

}).call(this);
