// Generated by CoffeeScript 1.8.0
(function() {
  window.types = {
    "Trello": ["card", "board", "at a glance", "Trello", "Taco", "lists", "list of lists", "checklists", "Chorizo", "Pete", "Trello Gold", "Business Class", "visual", "free", "attachment", "drag and drop", "members", "organization", "list", "with anyone", "anything", "label", "comment", "notifications", "done", "easy", "organize"],
    "Skate": ["Tony Hawk", "Bob Burnquist", "Steve Caballero", "Rune Glifberg", "Elissa Steamer", "Geoff Rowley", "Bucky Lasek", "Kareem Campbell", "Rodney Mullen", "Thrasher", "Vans", "180", "360", "540", "720", "900", "1080", "half-pipe", "full pipe", "downhill", "skate or die", "trucks", "S.K.A.T.E.", "50-50", "boneless", "nose slide", "nosegrind", "stoked", "rad", "goofy-footed", "crooked grind", "fakie", "pump", "ollie", "nollie", "tail", "grind", "bail", "fail", "gnarly", "manual", "spine", "lip", "rails", "airwalk", "shoveit", "heel flip", "mini ramp", "lien air", "varial", "method air", "frigid air", "kickflip", "McTwist", "drop in", "body varial"],
    "Hodor": ["hodor", "hodor", "hodor", "hodor", "hodor", "hodor", "HODOR", "Hodor"],
    "Escape": ["<p>", "<B>haxorz</B>", "<script>alert('1337')</script>", "</p>", "</html>", "<img src='/' width='500' height='300'>"]
  };

}).call(this);
